### PR TITLE
fix mem-burn process been killed too early by kernel oom_killer

### PR DESCRIPTION
**Pull request by buhuipao**
### Describe what this PR does / why we need it
when mem-burn in ram mode and reserve param is too small, the mem-burn process will be killed early before reaching the target retention value. so I write score_adj '-1000'  to mem-burn process oom_score_adj file.

### CODE REVIEW

**Comment by Mutated1994** [comment]
As far as I am concerned, it could be very dangerous.

In chinese:
很抱歉，我想提出一些我个人的看法。
这只是一个内存占用的故障，如果调低它的`oom_score_adj`，会加大一些无辜的进程被杀死的概率。
对于混沌工程来说，"最小爆炸半径"应该是可控的才对。

**Comment by xcaspar** [comment]
> As far as I am concerned, it could be very dangerous.
> 
> In chinese:
> 很抱歉，我想提出一些我个人的看法。
> 这只是一个内存占用的故障，如果调低它的`oom_score_adj`，会加大一些无辜的进程被杀死的概率。
> 对于混沌工程来说，"最小爆炸半径"应该是可控的才对。

之前遇到过一个线上故障，因一个运维进程占用内存过大，导致业务应用进程被干掉，这个 PR 更好模拟这个故障，但是最好将其抽取一个配置参数。

---

I have encountered an online failure before. Because an operation process occupies too much memory, the business application process is killed. This PR can better simulate the failure, but it is best to extract a configuration parameter.

**Comment by xcaspar** [comment]
@buhuipao Please modify the username used when committing. And can you extract a flag to enable this feature?

**Comment by Mutated1994** [comment]
> > As far as I am concerned, it could be very dangerous.
> > In chinese:
> > 很抱歉，我想提出一些我个人的看法。
> > 这只是一个内存占用的故障，如果调低它的`oom_score_adj`，会加大一些无辜的进程被杀死的概率。
> > 对于混沌工程来说，"最小爆炸半径"应该是可控的才对。
> 
> 之前遇到过一个线上故障，因一个运维进程占用内存过大，导致业务应用进程被干掉，这个 PR 更好模拟这个故障，但是最好将其抽取一个配置参数。
> 
> I have encountered an online failure before. Because an operation process occupies too much memory, the business application process is killed. This PR can better simulate the failure, but it is best to extract a configuration parameter.

Yep, I agree with you.

**Comment by buhuipao** [comment]
> @buhuipao Please modify the username used when committing. And can you extract a flag to enable this feature? Thanks~

Done.

**Comment by xcaspar** [comment]
@buhuipao OK, thanks for your contribution, I will review it this week.

**Pull request merged**
